// #include "config-debug.h"
#include "config-memmap.h"

#define CONFIG_FE8_REWRITE

// #define CONFIG_FE8SRR

// #define CONFIG_CROP_VANILLA_MSG

/* CommonProtection.event */
#define CONFIG_COMMON_PROTECTION_ENABLED

/* If comment, CHAX may not verify on FESKILL magic work in SRAM */
#define CONFIG_VERIFY_SKILLSYS_SRAM

/* If uncomment, use utf-8 characters */
#define CONFIG_USE_UTF8_GLYPH

// #define CONFIG_USE_COMBO_ATTACK

// #define CONFIG_BATTLE_SURROUND

#define CONFIG_KTUT_LEVEL 0

// #define CONFIG_USE_CHAR_CUSTOM_ANIM

#define CONFIG_FASTER_MAP_RANGE

// #define CONFIG_LEADER_SHIP_EN

// #define CONFIG_REMOVE_MOVE_PATH

// #define CONFIG_USE_GAIDEN_MAGIC

#ifdef CONFIG_USE_GAIDEN_MAGIC
	#define CONFIG_GAIDEN_MAGIC_MUST_BE_MAGIC 0 // 0: all weapons are okay
	#define CONFIG_GAIDEN_MAGIC_REQUIRES_WRANK 0 // 0: not requires unit ability to equip that weapon
	#define CONFIG_GAIDEN_MAGIC_AI_EN 1
	#define CONFIG_GAIDEN_EXT_CONF_EN 1
#endif /* USE_GAIDEN_MAGIC */

#define CONFIG_UNLOCK_ALLY_MHP_LIMIT

// #define CONFIG_INSTALL_KERNEL_SHIELD

#define CONFIG_TARGETTING_CURSOR_FRAMES

#define CONFIG_MAP_BATTLE_ANIM_FRAMES

#define CONFIG_INSTALL_SEND_INVENTORY_ON_DEATH

#define CONFIG_INSTALL_RES_TERRAIN_WINDOW

// #define CONFIG_INSTALL_NO_WAIT_AFTER_TRADING

#define CONFIG_INSTALL_VESLY_DEBUGGER

// #define CONFIG_INSTALL_EXTENDED_STAT_BARS

#define CONFIG_INSTALL_MENU_WIDTHS

// #define CONFIG_TEXT_ENGINE_REWORK

// #define CONFIG_TALK_MAP_ICON

#define CONFIG_INSTALL_PREPS_AUGURY

#define CONFIG_SHOW_HEAL_AMOUNT

#define CONFIG_QUINTESSANCE_EFFECT

// #define CONFIG_SUMMON_EXP

#define CONFIG_STAT_SCREEN_ALLEGIANCE_COLORS

#define CONFIG_VESLY_SUPPORT_POST_BATTLE

#ifdef CONFIG_VESLY_SUPPORT_POST_BATTLE
	#define SUPPORT_RATE_KILL 100
	#define SUPPORT_RATE_COMBAT 100
	#define SUPPORT_RATE_STAFF 100
	#define SUPPORT_RATE_DANCE 100
#endif

// #define CONFIG_FLIPPED_SPRITES

// #define CONFIG_AUTO_REPAIR_WEAPONS

// By Jester
#define CONFIG_STAT_SCREEN_TERRAIN_BONUS

// #define CONFIG_INSTANT_LEVEL_UP

#define CONFIG_S_RANK_NO_WEAPON_WEIGHT

// #define CONFIG_VESLY_RECLASS

// #define CONFIG_EXTENDED_HELPBOXES

// #define CONFIG_LAZBERIAN_TURN_FLOW

// #define CONFIG_LIMITED_SHOP_STOCK

// #define CONFIG_ARENA_LIMITS

// #define CONFIG_DANGER_RADIUS

#define CONFIG_TELLIUS_CAPACITY_SYSTEM
#define CONFIG_TELLIUS_CAPACITY_BASE 50
#define CONFIG_TELLIUS_CAPACITY_PROMOTED 25

// #define CONFIG_TALK_LEVEL_UP

// #define CONFIG_RESTORE_HP_ON_LEVEL_UP

// #define CONFIG_DEATH_DANCE

// #define CONFIG_INFINITE_DURABILITY

#define CONFIG_CHAPTER_NAMES_AS_TEXT

#define CONFIG_RESET_BWL_STATS_EACH_CHAPTER

/**
 * Levelup mode
 * 0: vanilla
 * 1: uncontrollable
 * 2: fixed
 * 3: 100%
 * 4: 0%
 */
#define CONFIG_LVUP_MODE_TUTORIAL 0
#define CONFIG_LVUP_MODE_NORMAL 0
#define CONFIG_LVUP_MODE_HARD 0

#define CONFIG_PAGE1_WITH_BWL 1
#define CONFIG_PAGE1_WITH_LEADERSHIP 0

#define CONFIG_PAGE3_SKILL_LAYOUT 1

#define CONFIG_PERFORMANCE_OPTIMIZATION

// #define CONFIG_INSTALL_MAPACTIONANIM

// #define CONFIG_INSTALL_FE6_STAT_SCREEN

// #define CONFIG_INSTALL_BOW2DECREASE

// #define CONFIG_INSTALL_DECREASE_HIT_AT_RANGE

// #define CONFIG_VESLY_AOE

// #define CONFIG_PROMOTE_ENEMIES_IF_KILLED_UNIT

// #define CONFIG_REFUGE_FEATURE

// #define CONFIG_ESCAPE_EVENT

/* BROKEN - DO NOT USE */
// #define CONFIG_AUTO_PROMOTION_ON_MAX_LEVEL

/* Don't turn this on until I have defeat quotes for everyone as MC dying without a quote doesn't trigger a game over screen */
//#define CONFIG_MULTIPLE_DEATH_QUOTES

#define CONFIG_GROWTHS_AS_LETTERS

// #define CONFIG_FOURTH_ALLEGIANCE

#define CONFIG_AFFINITY_SHOW_DESCRIPTIONS

#define CONFIG_INSTALL_CONVOYEXPA
#define CONFIG_INSTALL_CONVOYEXPA_AMT 200 // better not to touch this since it will affect on size of gExpaConvoyItemArray

#define CONFIG_AI_ACTION_AMT 20
#define CONFIG_AI_ACTION_EXPA_Teleportation 14

#define CONFIG_UNIT_ACTION_AMT 0x30
#define CONFIG_UNIT_ACTION_EXPA_ExecSkill 0x23
#define CONFIG_UNIT_ACTION_EXPA_GaidenMagicCombat 0x24
#define CONFIG_UNIT_ACTION_EXPA_GaidenMagicStaff 0x25

#define CONFIG_PR_ITEM_ICON  0x5926F4
#define CONFIG_ICON_INDEX_MAG_BOOSTER 0xCA
#define CONFIG_ICON_INDEX_STAR 0xCB
#define CONFIG_ICON_INDEX_SKILL_STEALER 0xCC
#define CONFIG_ICON_INDEX_ARMS_SCROLL 0xCD
#define CONFIG_ICON_INDEX_FORCE_STAFF 0xCE
#define CONFIG_ICON_INDEX_ACUITY_STAFF 0xD0
#define CONFIG_ICON_INDEX_FORTUNE_STAFF 0xD1
#define CONFIG_ICON_INDEX_IRON_STAFF 0xD2
#define CONFIG_ICON_INDEX_SPRINT_STAFF 0xD3
#define CONFIG_ICON_INDEX_TEMPEST_STAFF 0xD4

#define CONFIG_PR_ITEM_TABLE 0x809B10
#define CONFIG_ITEM_INDEX_MAG_BOOSTER 0xBC
#define CONFIG_ITEM_INDEX_SKILL_SCROLL 0xBD
#define CONFIG_ITEM_INDEX_SKILL_STEALER 0xBE
#define CONFIG_ITEM_INDEX_ARMS_SCROLL 0xBF
#define CONFIG_ITEM_INDEX_FORCE_STAFF 0xC0
#define CONFIG_ITEM_INDEX_ACUITY_STAFF 0xC1
#define CONFIG_ITEM_INDEX_FORTUNE_STAFF 0xC2
#define CONFIG_ITEM_INDEX_IRON_STAFF 0xC3
#define CONFIG_ITEM_INDEX_SPRINT_STAFF 0xC4
#define CONFIG_ITEM_INDEX_TEMPEST_STAFF 0xC5

#define CONFIG_UNIT_AMT_ALLY     51
#define CONFIG_UNIT_AMT_ENEMY    50
#define CONFIG_UNIT_AMT_NPC      8

#ifdef CONFIG_FOURTH_ALLEGIANCE
	#define CONFIG_UNIT_AMT_FOURTH   8
#endif

#define CONFIG_AUTO_NARROW_FONT

// #define CONFIG_CUSTOM_CHAPTER_SCREEN

// #define CONFIG_CUSTOM_GUIDE

// #define SETH_INJURED
// #define INJURED_TURN_COUNT 5

#define CONFIG_SUPPORT_REWARDS

#define CONFIG_GAMEOVER_QUOTES
//#define CONFIG_GAMEOVER_GENERIC
#define CONFIG_GAMEOVER_SPECIFIC
//#define CONFIG_GAMEOVER_COMEDIC