#ifndef TEXTS_H
#define TEXTS_H

/* Auto generated by: make text */
<<<<<<< HEAD
// #include "../../Contants/Texts/TextDefinitions.h"
#include "../../Contants/Texts/build/msgs.h"
=======
#include "../../Contents/Texts/build/msgs.h"
>>>>>>> 7b86e9495edda39a0eb0d27d352d8795a134d7fc

#endif /* TEXTS_H */
