#pragma once

enum MapTaskConfIndex {
	MTSKCONF_HPBAR,
	MTSKCONF_COMM_BUFF,
	MTSKCONF_COMM_DEBUFF,
	MTSKCONF_RESCUING,
	MTSKCONF_BOSS,
	MTSKCONF_PROTECTION,
	MTSKCONF_TALK_1,
	MTSKCONF_TALK_2,
	MTSKCONF_DROP_ITEM,
	MTSKCONF_WARNING,
	MTSKCONF_STATUS_SLOW,
	MTSKCONF_STATUS_BREAK,
	MTSKCONF_STATUS_TOXIC,
	MTSKCONF_STATUS_HIDE,
	MTSKCONF_STATUS_DECOY,
	MTSKCONF_STATUS_DOOM,
	MTSKCONF_STATUS_REPLICATE,
	MTSKCONF_STATUS_EFFECTIVE,
	MTSKCONF_STATUS_SHOCK,
	MTSKCONF_STATUS_PANIC,
	// MTSKCONF_STATUS_ENFEEBLE,
	// MTSKCONF_STATUS_PROVIDENCE,
	// MTSKCONF_STATUS_BOUND,
	// MTSKCONF_STATUS_HEX,

};

#include "common-chax.h"

struct MapTaskConf {
	u16 x, y;
	u16 *obj;
};

// extern struct MapTaskConf const gMapTaskConfs[];
extern struct MapTaskConf const *const gpMapTaskConfs;

// extern u8 const gHpBarChr[];
extern u8 const *const gpHpBarChr;

extern struct Vec2u MapTaskVec;

void MapTaskPutOamHi(int type, int oam2);
